method: bayes
name: ner_finetuning_sweep
program: wandb_sweep.py
metric:
  name: eval/loss
  goal: minimize
parameters:
  learning_rate:
    distribution: log_uniform_values
    min: 1e-5
    max: 1e-3
  batch_size:
    values: [1, 2, 4]
  num_train_epochs:
    values: [1, 1.5, 2, 2.5, 3]
  warmup_ratio:
    distribution: uniform
    min: 0.1
    max: 0.9
  r:
    values: [2, 4, 8, 16]
  lora_alpha:
    values: [16, 32, 64]
  lora_dropout:
    distribution: uniform
    min: 0.1
    max: 0.5
  system_prompt:
    values: ["Please identify all the named entities mentioned in the input sentence provided below. The entities may ONLY have categories \"Disease\" or \"Chemical\". You must output the results strictly as plain text in JSON format. Do not converse with the user, simply follow these instructions.\nExample user input and assistant response:\nUser:\nHowever, studies into the dose necessary to combating scopolamine. Effects of uninephrectomy and high protein feeding on lithium-induced chronic renal failure in rats.\nAssistant:\n[{\"category\": \"Chemical\", \"entity\": \"scopolamine\"}, {\"category\": \"Chemical\", \"entity\": \"lithium\"}, {\"category\": \"Disease\", \"entity\": \"chronic renal failure\"}]"]

